### ISSUE TITLE
Доработка сервиса картинок

### ISSUE THREAD

**Issue by muhazzz** [GolosChain/imagehoster#1]
1. Сделать из двух старых сервисов (imagehoster и imageproxy) один
2. Решить с хранилищем - отказаться от локального хранения в пользу object storage (нашего или стороннего), либо сделать локальное правильно (решить проблему с каталогами)
3. Горизонтальное масштабирование ресайза и реплицирование файлов (хотя бы двойное), чтобы в системе не было SPOF и всё продолжало работать даже при полной недоступности одного из ДЦ.
4. Cloud-native + Метрики

**Comment by bacher** [comment]
Проект и дока тут https://github.com/GolosChain/imghost
